### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by guyzk** [aeyrium/bezier-chart#11]
A few things to make the library even more amazing:

1) Interactive legends
For charts with multiple lines it would be great if there was an option to add legends on top of the chart.
The legends will get the same text as the labels in the bubble.
The legend shape and type could be one of 2 options 
a) Informative - A simple circle/square with the same color as the line next to the text (like a regular legend)
b) Interactive - A checkbox with the same color as the line that when checked will show/hide the line from the chart.

2) When using the monthly chart and the series is less than a year, the width is smaller than the screen width (or the charts given width). It could be awesome to get an option to force filling the charts width for a more professional look.

3) Hourly chart - A series of a 24 hour period showing the data per hour

**Comment by diegoveloper** [comment]
I could work now on the suggestion number 2,  could you add a simple code to reproduce what you mentioned? thanks

**Comment by guyzk** [comment]
You could use the same code as the "MONTHLY" sample on the pub.dev site.
There you have 8 months and you can see that the chart doesn't take up the whole width.
It get even worse if you have less months (try 5-6).

**Comment by diegoveloper** [comment]
You can just reduce the width size of the parent , I have to add margin to the left and right, otherwise the indicator would appear cut.

![Simulator Screen Shot - iPhone 8 - 2019-06-30 at 20 29 56](https://user-images.githubusercontent.com/4898256/60405497-34746400-9b76-11e9-8f9e-2ab8ac4c15c5.png)

```
Container(
      color: Colors.red,
      height: MediaQuery.of(context).size.height / 2,
      width: MediaQuery.of(context).size.width/1.2,
      child: BezierChart(
        bezierChartScale: BezierChartScale.MONTHLY,
        ...
```

**Comment by guyzk** [comment]
As I said the hourly chart is my most critical request.
Without it I sadly won't be able to use this library as it is essential for my company's app.
Tried using custom chart but it doesn't work as expected.
I hope you can add this very needed (and also requested by others) so that I wont have to go fishing for a different library

**Comment by diegoveloper** [comment]
Ok, could you tell me what will be your input for HOURLY chart? and what do you expect to see in the footer (X axis) ?

**Comment by guyzk** [comment]
Thanks for your reply.
Hourly charts are usually for a short timespan.
For me it is up to 24 hours back - but maybe some others use it for larger spans.
The date format I will use is 'd/M\nHH:mm' (I round the minutes to 00 = start of each hour).
eg:
  1/7       
10:00  

  1/7       
11:00  

etc...

startDate and toDate need to check for the time difference in hours instead of days.
I don't believe there is any use for pinching into this scale as it would get massive.

**Comment by diegoveloper** [comment]
I updated the package, Could you try using the dependency in this way:
```
bezier_chart:
    git: 
      url: git://github.com/aeyrium/bezier-chart.git
      ref: master
```
And run : `flutter packages upgrade`

Check the method `sample8` from main sample.

New date scale type added `BezierChartScale.HOURLY`

Let me knows if it works.

**Comment by guyzk** [comment]
First of all, thanks for your quick responses. It makes your library very reliable and it is a vital thing when choosing to work with a library in a commercial app.
Secondly, the hourly chart works very well with only one exception regarding the footer spacing.
As of now the footer texts are too close together and the texts overlap. I think it would be best to have the spacing same as the weekly chart -- horizontalSpacing = constraints.maxWidth / 7 -- and not --horizontalSpacing = constraints.maxWidth / 10 --

Thanks again!

**Comment by diegoveloper** [comment]
Done, run `flutter packages upgrade` and try again :)

**Comment by guyzk** [comment]
Amazing! Thanks!
