### ISSUE TITLE
Please fix intl to ^0.17.0 - conflicting package errors

### ISSUE THREAD

**Issue by calvintam236** [aeyrium/bezier-chart#114]
I am using other dependencies that requires `intl: ^0.17.0` but `bezier-chart` is using `intl: ^0.16.0`. Looks like someone made a PR #113 for this issue.

If anyone can fix (like merging that PR with a new version on pub.dev), it would be great!

**Comment by calvintam236** [comment]
@diegoveloper @ra9r can you help us on this?

**Comment by BrianMwas** [comment]
I also need to use the package

**Comment by burntblark** [comment]
This would be of great help actually. We are trying to move on to a null safe version and this issue is what is stopping us actually. Kindly help with this.

**Comment by calvintam236** [comment]
#117 has merged to master but not yet released on pub.dev.

https://pub.dev/packages/bezier_chart/versions

**Comment by burntblark** [comment]
How can we help move this forward. Let the community help with this.

**Comment by calvintam236** [comment]
Since it is currently in progress to publish it, I'm closing this. See #116 for status.
