### ISSUE TITLE
Potential bug/gotchas when using BezierChartScale.WEEKLY

### ISSUE THREAD

**Issue by delay** [aeyrium/bezier-chart#13]
Thanks so much for this charting library!  

I think I may have found a small bug…. Of course it may be by design so the chart doesn’t appear until you have multiple points to plot…

On BezierChartScale.WEEKLY

When adding the first point to a graph it will not appear.  I tracked it to this code…  Also I believe one point will be dropped from the graph with multiple points.

```
      for (int i = 0; i < days; i++) {
        final newDate = widget.fromDate.add(
          Duration(
            days: (i+1),
          ),
        );
```

I think it should be this.
```
      for (int i = 0; i  <= days; i++) { //otherwise will not show if only 1 and drop one of the points if more than 1 day?
        final newDate = widget.fromDate.add(
          Duration(
            days: (i), //remove +1 so dates match up with data points.
          ),
        );

```

There is also a second possible gotcha…
If the fromDate and toDate have less than 24 hours between them it will merge the dates, not necessarily by the right date.  I fixed this by dropping the hours:minutes:seconds from my DateTime Objects.  Maybe have something in the docs about it?  In any case I was able to fix that with the input data, but Dates might not match up as expected when using difference if points are less than 24 hours apart but appear on different days.  Here is that line: 
```
final days = widget.toDate
          .difference(widget.fromDate)
          .inDays;
```
 I think you could fix this by converting the fromDate and toDate to date only(no time value) and then getting the difference that way. 

Function to convert to date only (no time)…
```
DateTime convertToDateOnly(DateTime date) {
  int year = date.year;
  int month = date.month;
  int day = date.day;
  return DateTime(year, month, day);
}

```
Third and final potential gotcha.  If fromDate == toDate that isn’t allowed either so I  needed to add a second to the toDate if only one data point.  So that’s an easy fix too without changing the charting library. Not sure if you wanted to handle that in the library or not.

Anyway thanks for your really nice charting library.  This will save me so much time!

**Comment by diegoveloper** [comment]
Would be great if you add some sample codes to reproduce the issues . We are accepting PR's also :)

**Comment by delay** [comment]
Ok I will show an example and try to submit a PR for it. Not exactly sure if those changes would have unintended consequences elsewhere as I didn't go over all of your code.

**Comment by delay** [comment]
Ok I sent you the pull request.  The first commit is only to show the problem, the second commit is the actual fix..  Sorry I couldn't figure out how to separate this in my pull request...
