### ISSUE TITLE
How to use with external data

### ISSUE THREAD

**Issue by deedos** [aeyrium/bezier-chart#16]
Hi. I'm fetching my data from  an external source into a model inside my app. Do I need to convert this data model to a DataPoint model to make it work ? Are there examples on how to do it ?
many thanks in advance

**Comment by diegoveloper** [comment]
Yes, you need to convert your data into `DataPoint`,  you can find any sample from the web about how to get async data.

**Comment by deedos** [comment]
Thanks Diego! 
I have already my async data rendered through Flutter oficcial charts package so this part is already done. My doubt is about how to convert my model to DataPoint model. My values (temperature readings) is already a double type and my xAxis is a DateTime type as well.

**Comment by diegoveloper** [comment]
You can just check the samples in this repo,  https://github.com/aeyrium/bezier-chart/tree/master/example

**Comment by deedos** [comment]
Here there is a nice example about the issue: https://github.com/aeyrium/bezier-chart/blob/master/example/lib/sample10.dart

thanks
