### ISSUE TITLE
Bubble indicator more styling props

### ISSUE THREAD

**Issue by xylish7** [aeyrium/bezier-chart#20]
From what I saw, the only option to style the bubble indicator is using the **bubbleIndicatorColor** option, which only let you style the background of the bubble indicator.

The problem appears when I'm using a light theme and I need to make the bubble indicator **grey**, because white won't be a good choice.
**Example:**
![image](https://user-images.githubusercontent.com/24867712/61109479-a5c4e880-a48d-11e9-86f4-a9d0270235fc.png)
Now the label disappear because it's the same color as the background. It would be nice if you can add 3 more props:
![image](https://user-images.githubusercontent.com/24867712/61109889-b32ea280-a48e-11e9-836a-45e7cb2f791b.png)
1. TextStyle bubbleIndicatorTitleStyle
2. TextStyle bubbleIndicatorValueStyle
3. TextStyle bubbleIndicatorLabelStyle

**Comment by diegoveloper** [comment]
Done,  I updated the code, Could you try using the dependency in this way:
```
bezier_chart:
    git: 
      url: git://github.com/aeyrium/bezier-chart.git
      ref: master
```
And run : `flutter packages upgrade`

Check the `sample8` 

I'm ignoring the `fontSize` for now.

Let me knows if it works.

**Comment by xylish7** [comment]
It's perfect! Good job! 👍
