### ISSUE TITLE
Show current month and year

### ISSUE THREAD

**Issue by xylish7** [aeyrium/bezier-chart#21]
It would be very helpful to show the month and the year in the WEEKLY date format chart because, if you have many months shown on the chart you wouldn't know for what month are those days.
**Problem:**
![image](https://user-images.githubusercontent.com/24867712/61175306-9a6cdc80-a5b5-11e9-960a-4e1060939e6a.png)
In this case, you can't say which month and year is the shown date. A workaround would be this:
![image](https://user-images.githubusercontent.com/24867712/61175360-aa38f080-a5b6-11e9-9434-0a7b6f5ff1cb.png)
You could add 2 props:
- bool showMonth - which will show the month on X axis and at the begining of the X and Y axes
- bool showYear - which will show the year  at the begining of the X and Y axes

**Comment by diegoveloper** [comment]
Check the property: footerDateTimeBuilder   in BezierChartWidget .

**Comment by xylish7** [comment]
I see. It's a great prop, however I won't be able to put all those information in the chart and still have a nice design, or maybe i'm not using the prop corectly, but thank you for the information.
```dart
footerDateTimeBuilder: (DateTime value, BezierChartScale scaleType) {
            print(scaleType);
            final newFormat = intl.DateFormat('dd/MM/yyyy');
            return newFormat.format(value);
          }
```
**Results:**
![image](https://user-images.githubusercontent.com/24867712/61175519-a0fd5300-a5b9-11e9-9768-704b92ebe8f3.png)

**Comment by diegoveloper** [comment]
You could try adding a breakline "$date1\n$date2"

**Comment by xylish7** [comment]
Hmm, it's better like this. Thank you!
