### ISSUE TITLE
bezierChartScale CUSTOM accept DateTime type

### ISSUE THREAD

**Issue by deedos** [aeyrium/bezier-chart#28]
When using my DateTime data for xAxisand bezierChartScale: BezierChartScale.CUSTOM, I get an error (accepts only doubles):

> lib/ui/common/logchart.dart:141:40: Error: The argument type 'List<DateTime>' can't be assigned to the parameter type 'List<double>'

How can i have my filters (querys) to scale ?

many thanks

**Comment by diegoveloper** [comment]
Yes, custom scale only accept double values but you can use
footerValueBuilder to display a custom footer.
