### ISSUE TITLE
How make onMissingValue return previous value?

### ISSUE THREAD

**Issue by zeucxb** [aeyrium/bezier-chart#29]
`onMissingValue` just receive a dateTime as param, how can I return previous value when missing value?

**Comment by diegoveloper** [comment]
what do you mean? Could you explain what do you want to do ?  `onMissingValue` is a builder that you can use to return a value when there is no value for a specific DateTime.

**Comment by zeucxb** [comment]
I have a list of values and a interval is missing, so I want to return the previous value.

ex. [11-01-2019 -> 1, 01-01-2020 -> 3]

I want to show:

11-01-2019 -> 1
12-01-2019 -> 1
01-01-2020 -> 3

not:

11-01-2019 -> 1
12-01-2019 -> 0
01-01-2020 -> 3

**Comment by diegoveloper** [comment]
what is the code of the builder `onMissingValue` that you are using ?

**Comment by zeucxb** [comment]
```dart
onMissingValue: (DateTime dateTime) {
                double lastValue = 0;

                for (final dataPoint in data) {
                  if (dataPoint.xAxis.isBefore(dateTime)) {
                    lastValue = dataPoint.value;
                    break;
                  }
                }

                return lastValue;
              },
```

**Comment by diegoveloper** [comment]
did you debug your code?

**Comment by zeucxb** [comment]
What do you mean?

**Comment by diegoveloper** [comment]
check if the condition is executed

**Comment by zeucxb** [comment]
Yes, it's the graph is working well, I just wanna know if there are a better way, because I create loop just to return the previous value in the graph.

**Comment by diegoveloper** [comment]
ahh, no sorry, that feature is not implemented but we are accepting Pull requests :).
Also you can improve your loop using HashMaps to reduce the complexity.
