### ISSUE TITLE
Add more time scale options

### ISSUE THREAD

**Issue by synw** [aeyrium/bezier-chart#3]
Hi, great package. Would it be possible to add more time scale options: daily, hourly and minutely please?

**Comment by diegoveloper** [comment]
If you use the custom scale, you can customize the X axis.

**Comment by synw** [comment]
This is not just about the axis labels. I have long series of daily data and CUSTOM does not zoom and nicely reshape the data and labels like with the other predefined scales. Example screenshot:

![4](https://user-images.githubusercontent.com/12034394/59561088-2b7a8300-900b-11e9-966a-cd753beb9bd6.png)

The CUSTOM scale works with `xAxisCustomValues` and `footerValueBuilder` but when I try to use `fromDate` and `toDate` I get an assertion error:

> Unhandled Exception: 'package:bezier_chart/src/bezier_chart_widget.dart': Failed assertion: line 58 pos 11

This one:

```dart
assert(
  (bezierChartScale == BezierChartScale.CUSTOM &&
          xAxisCustomValues != null &&
          series != null) ||
      bezierChartScale != BezierChartScale.CUSTOM,
  "The xAxisCustomValues and series must not be null",
),
```

I don't get it. Did I miss something here? I would like to take advantage of the horizontal scrolling with my daily data (and possibly later for other time scales like hour or minute).

**Comment by diegoveloper** [comment]
Hmm maybe I could add the zoom to custom values type.
The issue with hours for the scale is the data will be hugeeee from two
dates 2018 vs 2019

**Comment by synw** [comment]
Maybe you can limit the zoom level depending on the scale: and hourly scale does not need yearly level zoom. As I said what would be ideal is to have these other scale levels and not use CUSTOM because it handles automatically the x axis labels with datetimes, which I think is a great advantage for charting timeseries.

**Comment by guyzk** [comment]
Yes. Definitely can use a daily scale in my app.
This feature will be most welcome!

**Comment by diegoveloper** [comment]
The Weekly type works as a daily Chart ,  what do you mean?

**Comment by guyzk** [comment]
What i need is a past 24 hours timescale. Is it possible?
As @synw mentioned, using the custom scale does not handle the x axis label automatically with datetimes...

**Comment by diegoveloper** [comment]
I updated the package, Could you try using the dependency in this way:
```
bezier_chart:
    git: 
      url: git://github.com/aeyrium/bezier-chart.git
      ref: master
```
And run : `flutter packages upgrade`

Check the method `sample8` from main sample.

New date scale type added `BezierChartScale.HOURLY`

Let me knows if it works.
