### ISSUE TITLE
When use footerValueBuilder, popup bubble don't show the same text.

### ISSUE THREAD

**Issue by zeucxb** [aeyrium/bezier-chart#30]
When I change the bottom text with `footerValueBuilder` should update the popup bubble text.

**Comment by diegoveloper** [comment]
It's only for the footer, but you are right, we will need a builder for the bubble.

**Comment by zeucxb** [comment]
Yes, or be able to disable indicator in the bubbler. Because, if change the footer, sometimes bubbler indicator do not make sense. (They look not related).

**Comment by zeucxb** [comment]
Just more one thing, can I fix a popup bubble or something that show the value?

**Comment by diegoveloper** [comment]
You could fork the project do your changes and send a Pull request (without
breaking the current behaviour).

**Comment by zeucxb** [comment]
So, currently there is not way to "always show" popup bubble, right?

**Comment by diegoveloper** [comment]
What do you mean?

**Comment by zeucxb** [comment]
I want something like this:

![Screenshot_2019-08-01-11-31-46-964_com resultadodotreino](https://user-images.githubusercontent.com/11702749/62344827-001dfb80-b4c6-11e9-9132-10581ad303d4.png)

**Comment by diegoveloper** [comment]
This package supports multiline graph, so what do we do in that case?

**Comment by zeucxb** [comment]
If multiline, it should show values on tap (select) line.

**Comment by diegoveloper** [comment]
Ok, I will leave this issue open in case anyone want to implement it
without breaking the current behavior.

**Comment by diegoveloper** [comment]
there are new changes about custom labels inside bubble indicator:  https://github.com/aeyrium/bezier-chart/pull/40
