### ISSUE TITLE
More parameters in BezierChartScale

### ISSUE THREAD

**Issue by KyllianDM** [aeyrium/bezier-chart#33]
Hello,
Could you please include the Daily parameter in BezierChartScale ?

Thanks !

**Comment by KyllianDM** [comment]
And, could you also include 15min and 30min parameters ?
Thank you very much !

**Comment by diegoveloper** [comment]
There is a new scale   : BezierChartScale.HOURLY , that you could use

**Comment by KyllianDM** [comment]
Hello, I saw this option but I would also need a Daily parameter.

**Comment by diegoveloper** [comment]
there is a WEEKLY scale :)

**Comment by yaizudamashii** [comment]
Please add DAILY scale, weekly scale does not work because it sums multiple days' y-axis values of that week and coalesce into one data point.

**Comment by yaizudamashii** [comment]
Sorry, what I wrote is inaccurate.  In weekly, y axis values of the same day is coalesced into same day, which, for example, if a value was entered twice for the day, it becomes a sum of those values
