### ISSUE TITLE
[Question] - xAxis DateTime localization

### ISSUE THREAD

**Issue by angel1st** [aeyrium/bezier-chart#35]
Hi there, is it possible to localize `xAxis` values when they are from `DateTime` type?

**Comment by diegoveloper** [comment]
You can use `footerDateTimeBuilder`  https://github.com/aeyrium/bezier-chart/blob/master/example/lib/main.dart#L334

**Comment by angel1st** [comment]
@diegoveloper - thanks, man, this does the trick. How to apply the same for the tooltip, and have it localized as well?

**Comment by diegoveloper** [comment]
hmm there is no way to do this now, but we are accepting pull requests

**Comment by angel1st** [comment]
@diegoveloper re the tooltip / bubble localization, I believe the best course of action is to add two additional callbacks similar to `footerValueBuilder` and `footerDateTimeBuilder` - we can call them `bubbleLabelValueBuilder` and `bubbleLabelDateTimeBuilder`.
Then at the beginning of `_getInfoTitleText`, we can add:

    if (bubbleLabelValueBuilder!= null && scale == BezierChartScale.CUSTOM) {
      return bubbleLabelValueBuilder(_currentXDataPoint.value);
    }
    if (bubbleLabelDateTimeBuilder!= null && scale != BezierChartScale.CUSTOM) {
      return bubbleLabelDateTimeBuilder(_currentXDataPoint.xAxis as DateTime, scale);
    }

that should suffice.
What do you think?

**Comment by diegoveloper** [comment]
You can try and let us know if it works

**Comment by angel1st** [comment]
@diegoveloper - from which branch should I create a pull request?
I am trying from **master** branch, but it does not seem to be permitted...

![pull_request](https://user-images.githubusercontent.com/8547131/63208620-22776200-c0df-11e9-8a79-47307fee58b8.png)

**Comment by angel1st** [comment]
@diegoveloper - [done](https://github.com/aeyrium/bezier-chart/pull/40)
