### ISSUE TITLE
[Question] - is it possible to control yAxis total value when BezierChartScale.MONTHLY

### ISSUE THREAD

**Issue by angel1st** [aeyrium/bezier-chart#38]
Hi there
Let's, have the following  series:

            data: [
              DataPoint<DateTime>(value: 10, xAxis: date1),
              DataPoint<DateTime>(value: 50, xAxis: date2),
            ],

where `date1` and `date2` are within the same month. Then, if I switch to `BezierChartScale.MONTHLY` scale, for the specific month, I will see `yAxis` = 60, which essentially is the sum of the two values. 
This works fine, in case y values meaning make sense to be summed up e.g. they are prices.
In my case however, each y value is measured weight for a specific day. Hence I would like for instance to have average value of all weights for the month, when switch to `MONTHLY` scale.
Is that possible and if not, can you direct me to the source lines, when this calculation takes place?
Thanks!

**Comment by diegoveloper** [comment]
Check the `_computeSeries` method : https://github.com/aeyrium/bezier-chart/blob/master/lib/src/bezier_chart_widget.dart#L470
