### ISSUE TITLE
[Question] - is it possible to show data points only in case real y value is provided

### ISSUE THREAD

**Issue by angel1st** [aeyrium/bezier-chart#39]
Hi there,
I wonder if the chart can be configured to show data points on the curve only in case data series provide y value for specific x value? In case the y value is provided from `onMissingValue` callback, the point should not be drawn onto the curve. Again in case this is not possible (as I suspect), could be so kind to direct me to the code, so I can see if I can tweak it?
Thanks!

**Comment by diegoveloper** [comment]
hmm I don't understand the question, could you add an image about what you need?

**Comment by angel1st** [comment]
Sure, take a look below:

![Screenshot_1566015702](https://user-images.githubusercontent.com/8547131/63206618-d5849300-c0c0-11e9-98b4-0c60ee2ef5b1.png)

On the screen, point **A** is from `series.data` list as provided, when `BezierChart` is created. Point **B** however is provided from `onMissingValue` callback. I would like only type **A** y values to have point drawn onto the curve. Type **B** will still be visible as values, but won't have the circle graphical point drawn to the curve.
Does it sound clear now?

**Comment by diegoveloper** [comment]
ok, I sent some changes

Could you try using the dependency in this way:
```
bezier_chart:
    git: 
      url: git://github.com/aeyrium/bezier-chart.git
      ref: master
```
And run : `flutter packages upgrade`

check the `sample3` , there is a new property:  
```
 BezierChartConfig(
          displayDataPointWhenNoValue: false,
         ...
```

**Comment by angel1st** [comment]
thanks, @diegoveloper - that's exactly what I need. Thanks, man!
It seems however, there is an exception thrown, when I scroll to the leftmost chart side. Here is the output:

> I/flutter (31612): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (31612): The following NoSuchMethodError was thrown during paint():
I/flutter (31612): The getter 'value' was called on null.
I/flutter (31612): Receiver: null
I/flutter (31612): Tried calling: value
I/flutter (31612): 
I/flutter (31612): When the exception was thrown, this was the stack:
I/flutter (31612): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
I/flutter (31612): #1      _BezierChartPainter.paint (package:bezier_chart/src/bezier_chart_widget.dart:1193:30)
I/flutter (31612): #2      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:528:13)
I/flutter (31612): #3      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:566:7)
I/flutter (31612): #4      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2089:7)
I/flutter (31612): #5      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:172:13)
I/flutter (31612): #6      RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
I/flutter (31612): #7      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2089:7)
I/flutter (31612): #8      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:172:13)
I/flutter (31612): #9      RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
I/flutter (31612): #10     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2089:7)
I/flutter (31612): #11     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:172:13)
I/flutter (31612): #12     _RenderSingleChildViewport.paint.paintContents (package:bezier_chart/src/my_single_child_scroll_view.dart:338:17)
I/flutter (31612): #13     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:369:12)
I/flutter (31612): #14     PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:393:7)
I/flutter (31612): #15     _RenderSingleChildViewport.paint (package:bezier_chart/src/my_single_child_scroll_view.dart:344:17)
I/flutter (31612): #16     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2089:7)
I/flutter (31612): #17     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:127:11)
I/flutter (31612): #18     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
I/flutter (31612): #19     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:858:29)
I/flutter (31612): #20     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:348:19)
I/flutter (31612): #21     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter (31612): #22     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
I/flutter (31612): #23     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
I/flutter (31612): #24     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
I/flutter (31612): #25     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
I/flutter (31612): #29     _invoke (dart:ui/hooks.dart:236:10)
I/flutter (31612): #30     _drawFrame (dart:ui/hooks.dart:194:3)
I/flutter (31612): (elided 3 frames from package dart:async)
I/flutter (31612): 
I/flutter (31612): The following RenderObject was being processed when the exception was fired: RenderCustomPaint#4c812 relayoutBoundary=up22:
I/flutter (31612):   creator: CustomPaint ← Align ← Padding ← _SingleChildViewport ← IgnorePointer-[GlobalKey#3111a] ←
I/flutter (31612):     Semantics ← Listener ← _GestureSemantics ←
I/flutter (31612):     RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#7645f] ← Listener ← _ScrollableScope
I/flutter (31612):     ← _ScrollSemantics-[GlobalKey#46761] ← ⋯
I/flutter (31612):   parentData: offset=Offset(0.0, 102.6) (can use size)
I/flutter (31612):   constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=603.4)
I/flutter (31612):   size: Size(5147.2, 482.7)
I/flutter (31612): This RenderObject has no descendants.
I/flutter (31612): ═══════════════════════════════════════════════════════════════

**Comment by diegoveloper** [comment]
In the sample3?

**Comment by angel1st** [comment]
yep, here it is, slightly modified:
```

Widget sample3(BuildContext context) {
  final fromDate = DateTime(2019, 05, 22);
  final toDate = DateTime.now();
  final date1 = DateTime.now().subtract(Duration(days: 2));
  final date2 = DateTime.now().subtract(Duration(days: 3));
  return Center(
    child: Container(
      color: Colors.red,
      //height: MediaQuery.of(context).size.height / 2,
      //width: MediaQuery.of(context).size.width,
      child: BezierChart(
        fromDate: fromDate,
        bezierChartScale: BezierChartScale.WEEKLY,
        toDate: toDate,
        onIndicatorVisible: (val) {
          print("Indicator Visible :$val");
        },
        onDateTimeSelected: (datetime) {
          print("selected datetime: $datetime");
        },
        selectedDate: toDate,
        //this is optional
        footerDateTimeBuilder: (DateTime value, BezierChartScale scaleType) {
          final newFormat = intl.DateFormat('dd/MMM', "bg_BG");
          return newFormat.format(value);
        },
        series: [
          BezierLine(
            label: "Duty",
            onMissingValue: (dateTime) {
              if (dateTime.day.isEven) {
                return 10.0;
              }
              return 5.0;
            },
            data: [
              DataPoint<DateTime>(value: 30, xAxis: fromDate),
              DataPoint<DateTime>(value: 20, xAxis: date1),
              DataPoint<DateTime>(value: 50, xAxis: date2),
            ],
          ),
        ],
        config: BezierChartConfig(
          displayDataPointWhenNoValue: false,
          verticalIndicatorStrokeWidth: 3.0,
          pinchZoom: false,
          verticalIndicatorColor: Colors.black26,
          showVerticalIndicator: true,
          verticalIndicatorFixedPosition: false,
          backgroundColor: Colors.red,
        ),
      ),
    ),
  );
}

```

**Comment by angel1st** [comment]
... and here is my `flutter doctor -v` output:

> [√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17763.678], locale en-US)
    • Flutter version 1.7.8+hotfix.4 at E:\DevTools\flutter
    • Framework revision 20e59316b8 (4 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at E:\DevTools\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_SDK_ROOT = E:\DevTools\Android\Sdk
    • Java binary at: E:\DevTools\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

> [√] Android Studio (version 3.4)
    • Android Studio at E:\DevTools\android-studio
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

> [√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

> • No issues found!

**Comment by diegoveloper** [comment]
done, can you pull again?

**Comment by angel1st** [comment]
Thanks, @diegoveloper - it seems the exception is gone. I can see however another issue, related to y axis values - the topmost is cut off now. I guess this issue was introduced when #34 has been fixed.
See the screenshot below:

![Screenshot_1566143979](https://user-images.githubusercontent.com/8547131/63227030-c8fc5980-c1ea-11e9-9867-494304899d92.png)

shall I file a separate issue?

**Comment by diegoveloper** [comment]
Could you add a simple code to reproduce the problem?

**Comment by angel1st** [comment]
Not able to reproduce into a separate example, however, I found another y axis related issue, so I filed #44 
I am closing this issue, since it is fixed.

**Comment by JWong1105** [comment]
why not add this config (displayDataPointWhenNoValue)  to the newest version? it is useful.
