### ISSUE TITLE
Y axis labels

### ISSUE THREAD

**Issue by synw** [aeyrium/bezier-chart#4]
Is it possible to add some y axis labels?

**Comment by diegoveloper** [comment]
For now, there is a boolean property to display the Y axis value.
I could add a custom label for each value.

**Comment by diegoveloper** [comment]
Try using displayYAxis true from BezierChartConfig

**Comment by synw** [comment]
I missed that option, thanks. Still having an y axis problem:

![3](https://user-images.githubusercontent.com/12034394/59560750-5c0bee00-9006-11e9-891b-edbd200aaf99.png)

Is there any option to start the y axis at a non zero value? I did not find one

**Comment by diegoveloper** [comment]
Hmm I can't understand. Could you give me more information about what you
need?
Maybe a screenshot/image.

Thanks

**Comment by synw** [comment]
I have values starting at 100 and max at  114. If the axis y starts at zero there is a big space below the chart so it is not very readable and the y axis labels overlap each other. 

There is a screenshot in the previous post: https://user-images.githubusercontent.com/12034394/59560750-5c0bee00-9006-11e9-891b-edbd200aaf99.png

**Comment by diegoveloper** [comment]
Ok now I understand.

If you can tell me some ideas about how you would like to display that data
that would be great.

**Comment by synw** [comment]
I would like the y axis to start at something like 90 or so, then my line could occupy the whole space and be much more readable, and the labels visible. Maybe a `nonZeroYaxis` option or something like that. 

If it could automatically infer the y axis labels start value from my data, not having to provide one it would be ideal (most of the time I don't know what the data will be like at the time of chart definition, grabbing it from a database).

**Comment by diegoveloper** [comment]
I pushed some changes, try using the git repo directly , `startYAxisFromNonZeroValue` was added , is true by default, so you don't have to do anything.

Change your pubspec.yaml
```  
  bezier_chart:
    git: https://github.com/diegoveloper/bezier_chart.git
```

**Comment by synw** [comment]
Your pubspec specification was not working, I used this:

```
bezier_chart:
    git: 
      url: git://github.com/aeyrium/bezier-chart.git
      ref: master
```

Unfortunately it does not change anything, even if I set `startYAxisFromNonZeroValue` to true manually

**Comment by diegoveloper** [comment]
You should run: flutter packages upgrade

It's working for me

**Comment by synw** [comment]
It does not work well for me: it does when I zoom to some levels but not by default or with custom. I'll setup a dedicated test project for this to give a better report as soon as I have a bit of time. Btw the labels do not auto auto adjust on the y axis: when there are a lot of datapoints too many labels appear, but this is another problem to see later. 
Thanks for the good reactivity on the issues anyway. I'll post a more detailed report to be able to reproduce.

**Comment by kkroid** [comment]
startYAxisFromNonZeroValue  not working

**Comment by diegoveloper** [comment]
@kkroid what version are you using ? could you add a simple code to reproduce the issue ?

**Comment by Katekko** [comment]
@kkroid When you pass false to startYAxisFromNonZeroValue, the chart is going to start from zero otherwise your minimum value is the very first point in the chart, is working well for me.

**Comment by Katekko** [comment]
@diegoveloper I guess the pinch zoom is not working, when I pass false in pinchZoom nothing is happening ... I want to disable that functionality

**Comment by diegoveloper** [comment]
It's working if you use the repo git directly in your pubspec, I don't
publish a new version yet, it should be ready in one hour.

**Comment by diegoveloper** [comment]
I pushed some changes, could you try using :

```
bezier_chart:
    git: 
      url: git://github.com/aeyrium/bezier-chart.git
      ref: master
```

After that run : `flutter packages update`

And let me know it all works for your? 

Thanks

**Comment by Katekko** [comment]
Yep, pinchZoom is working fine now

But I think I will now use that lib, cause' I need more flexibility in configurations...  I guess I will need write some code to do something more simple and customizable.

Btw your lib is awesome, good work!!!!
