### ISSUE TITLE
[Question] - is it possible to update fromDate / toDate params dynamically?

### ISSUE THREAD

**Issue by angel1st** [aeyrium/bezier-chart#45]
In my understanding, `fromDate` / `toDate` pair allows to define useful timespan over the existing data series, meaning even though the time series can include date point before `fromDate` or after `toDate`, they won't be visible on the chart. So far so good.
Now, what I would like to achieve is to change let's say `fromDate` value and this to reflect over the date points visibility.
To be more specific, let's suppose `fromDate = DateTime(2019, 07, 1)` and I have following data series (`bezierChartScale: BezierChartScale.WEEKLY,`):

```
[
   DataPoint<DateTime>(value: 45.5, xAxis: DateTime(2019, 7, 25)), //  point 1
   DataPoint<DateTime>(value: 48.5, xAxis: DateTime(2019, 7, 30)), // point 2
   DataPoint<DateTime>(value: 45.5, xAxis: DateTime(2019, 8, 25)), // point 3
   DataPoint<DateTime>(value: 48.5, xAxis: DateTime(2019, 8, 30)), // point 4
]
```
In this case, all 4 points will be present on the chart.
Now, let's change `fromDate = DateTime(2019, 08, 1)`, then, I should see only points 3 & 4.
This one works however only in case the widget where chart is built is initially created.
In case this is `StatefulWidget` and I make

```
setState(() {
  fromDate = DateTime(2019, 08, 1);
});
```
I expected to see chart updated, however it didn't affect the chart.

**Comment by angel1st** [comment]
I found out how to handle the case - I can make a PR, in case your are ok with it...

**Comment by diegoveloper** [comment]
Ok

**Comment by angel1st** [comment]
done
