### ISSUE TITLE
Start drawing the line without zero value

### ISSUE THREAD

**Issue by synw** [aeyrium/bezier-chart#5]
The first point of the line seems to be always zero and this gives a vertical line connected to the first datapoint. Your example with increased numbers:

![1](https://user-images.githubusercontent.com/12034394/59558813-78019680-8fea-11e9-8ac6-7d42b2ec95ca.png)

Another example with a little more data:

![2](https://user-images.githubusercontent.com/12034394/59558816-91a2de00-8fea-11e9-9da0-fefc44eff395.png)

The dataset used:

`
[value: 100.25, xAxis: 1.0, value: 103.12, xAxis: 2.0, value: 108.0, xAxis: 3.0, value: 103.06, xAxis: 4.0, value: 103.0, xAxis: 5.0, value: 106.25, xAxis: 6.0, value: 108.0, xAxis: 7.0, value: 105.25, xAxis: 8.0, value: 107.69, xAxis: 9.0, value: 108.62, xAxis: 10.0, value: 107.0, xAxis: 11.0, value: 109.0, xAxis: 12.0, value: 110.0, xAxis: 13.0, value: 112.75, xAxis: 14.0, value: 113.5, xAxis: 15.0]`

The line between the two fist points of the chart is not vertical here because I started my labels at 1, 
How can I avoid displaying the first zero value to get a readable chart?

**Comment by diegoveloper** [comment]
What version of the package are you using?

**Comment by synw** [comment]
1.0.7: I was late. Tried with 1.0.8 and the vertical line problem is fixed. Now I still have to figure out how to display an y axis that does not start from zero to get a readable chart
