### ISSUE TITLE
Add an aggregation option

### ISSUE THREAD

**Issue by Peda1996** [aeyrium/bezier-chart#56]
Would it be possible to add an option, where one can set an aggregation method besides sum?

**Comment by diegoveloper** [comment]
sure, Pull requests are welcome :)

**Comment by Peda1996** [comment]
Well, should be working ;)
https://github.com/aeyrium/bezier-chart/pull/57

**Comment by Peda1996** [comment]
How can the version be updated?

**Comment by diegoveloper** [comment]
Can you modify the changelog?

**Comment by Peda1996** [comment]
After changing the changelog, the widget is automatically updated?

**Comment by diegoveloper** [comment]
no, I have to increase the version and publish again, but before do that ,
could you update the changelog with your latest changes?

**Comment by Peda1996** [comment]
https://github.com/aeyrium/bezier-chart/pull/58

**Comment by diegoveloper** [comment]
great! , I will publish a new version in a few hours,  for now you can use the repo directly
