### ISSUE TITLE
Suggested Features

### ISSUE THREAD

**Issue by wilscott** [aeyrium/bezier-chart#6]
Would it be possible to add the options below? 

- Display a vertical indicator at each x-value, instead of only the selected value. 

- Apply the gradient to only the space below the curve. Not the entire background.

**Comment by diegoveloper** [comment]
For the 1st request you can try the last version or use the git repo
directly in your pubspec.yaml

**Comment by wilscott** [comment]
@diegoveloper Thanks. I'll give it a try.

**Comment by wilscott** [comment]
@diegoveloper I check out the older repository and can't seem to identify how to make the vertical indicator appear on each x-axis value. Can you elaborate on how I can do this? I have attached a screenshot of what I want to accomplish. 
![graph_cropped](https://user-images.githubusercontent.com/48245107/59675221-206b5280-91c5-11e9-8373-310fa29a3d51.png)

**Comment by diegoveloper** [comment]
Did you try the sample7 ?

https://github.com/aeyrium/bezier-chart/blob/master/example/lib/main.dart

**Comment by wilscott** [comment]
Yes. There are no vertical lines on the x-axis. I set the parameter below. Are there any additional parameters I need to pass?

                  showVerticalIndicator: true,

**Comment by diegoveloper** [comment]
Ah no, it is just for the left side.
There is another property to display tje vertical line, check all the
samples.
It works only for the value selected, gradient below the line is not
implemented.

**Comment by wilscott** [comment]
Oh, yeah, I know how to show the single vertical selector. I was asking if there is an option to show one on every x-value at the same time. Like my screenshot. But I guess not.

**Comment by diegoveloper** [comment]
hmm it's a valid feature but what if we display more than one bezier line in the chart? how the vertical line should be displayed?

**Comment by wilscott** [comment]
Yeah that's a tricky one. Maybe provide the option to have a different
color for each bezier vertical bar. Or only allow it when there is one
curve.

**Comment by diegoveloper** [comment]
you mean, something like this  ? 

![Simulator Screen Shot - iPhone 8 - 2019-06-19 at 15 07 44](https://user-images.githubusercontent.com/4898256/59796862-094f6200-92a4-11e9-8f51-a29e149d2f06.png)

**Comment by wilscott** [comment]
Yes. Exactly that.

**Comment by diegoveloper** [comment]
Ok, follow these steps:

in your `pubspec.yaml` file change the dependency to

```
bezier_chart:
    git: 
      url: git://github.com/aeyrium/bezier-chart.git
      ref: master
```
after that , run

```
flutter packages upgrade
```

And you can check the sample7 : https://github.com/aeyrium/bezier-chart/blob/master/example/lib/main.dart#L606

**Comment by wilscott** [comment]
Ok. Thanks. I will test it out today.

**Comment by wilscott** [comment]
@diegoveloper It works perfectly. Thanks!
