### ISSUE TITLE
[Question] The Data Points are not updated.

### ISSUE THREAD

**Issue by youssefgamal84** [aeyrium/bezier-chart#62]
I fetch the values of the data points of my line from an online database. and I update the chart inside a setState(), but the widget on the screen does not change unless I long press a point. i.e. it doesn't change automatically.

**Comment by diegoveloper** [comment]
Could you add a simple code to reproduce the issue?

**Comment by forcegage-pvm** [comment]
I am also experiencing this issue. I have attached a sample widget which demonstrates this.

[bezierChart.zip](https://github.com/aeyrium/bezier-chart/files/4103031/bezierChart.zip)

**Comment by diegoveloper** [comment]
Thanks for the code, finally I could reproduce the issue , it's already fixed. Try using the repo in this way for now:

```
bezier_chart:
    git:
      url: https://github.com/aeyrium/bezier-chart
```

And change your sample rebuilding the List, like this : 
```
series: [
        BezierLine(data: List<DataPoint>.from(cdata)),
      ],
```

**Comment by forcegage-pvm** [comment]
Hi, that has fixed the issue, thanks
