### ISSUE TITLE
Touch not showing tooltip on selected point.

### ISSUE THREAD

**Issue by hardypatel30** [aeyrium/bezier-chart#65]
I am not sure why, But On touch of particular point, it is not showing tooltip data on the chart.

**Comment by diegoveloper** [comment]
could you add a sample to reproduce the issue?

**Comment by dienretry** [comment]
It is not showing any tool tips for me either I am copying the examples from the readme directly.

**Comment by diegoveloper** [comment]
Give us additional data.
Version of the package?
Flutter doctor?
Device tested?

**Comment by dienretry** [comment]
Thanks for the quick answer!

bezier_chart: "^1.0.15"
tested on a galaxy s9+
flutter doctor: 
`[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [version 10.0.18362.535], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at D:\flutter
    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at ---\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] VS Code (version 1.41.0)
    • VS Code at ---\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • SM G965F • 23b8eab507017ece • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
Process finished with exit code 0`

**Comment by diegoveloper** [comment]
I tested the samples inside the package and it's working fine on iOS simulator,   did you try the same samples? do you have any error on the log console ?

**Comment by dienretry** [comment]
yes, the same samples from the readme and no console erros, maybe its something android specific with the touch control

**Comment by diegoveloper** [comment]
Hmm I tested on android device os 10. and It's working fine too. 
Well I'm on flutter dev branch now. 
Try using another device and see if you can reproduce the error.

**Comment by bettkipronoh** [comment]
Actually this issue still exista
