### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by wilscott** [aeyrium/bezier-chart#7]
Sorry, couldn't find your email address, so posting here. @diegoveloper are you and/or your team interested in freelance work? I may have a project you can assist with. If interested, let me know the best place to discuss.

**Comment by diegoveloper** [comment]
Hello, my mail is the same as my username(diegoveloper@gmail.com). For now we are not doing freelance jobs, but you can find flutter developers on this group: https://www.facebook.com/groups/425920117856409/

Thanks
