### ISSUE TITLE
Apache

### ISSUE THREAD

**Issue by bootstraponline** [aeyrium/bezier-chart#70]
Any chance to change to Apache license?

**Comment by ra9r** [comment]
Why is that important to you?

**Comment by bootstraponline** [comment]
I am not able to use GPL in my projects.

**Comment by ra9r** [comment]
Understood ... but do you know what aspect of the license prevents you from using GPL 3.0?  Other than Apache what other licenses can you work with?

**Comment by bootstraponline** [comment]
In general there's a preference for Apache based on license data. GPL is great, just means not everyone will be able to use the library. Most large companies don't allow GPL dependencies.

For flutter projects, I'm only using permissively (MIT, BSD, Apache, etc.) licensed packages.

https://techcrunch.com/2011/05/17/developers-prefer-gpl-enterprises-prefer-apache/

**Comment by ra9r** [comment]
For what it is worth, GPL 3.0 is VERY different from the original GPL.  It is effectively no different than many of the other common license.  Enterprises have been slow to update their policies.  Not your problem I know. :)

I take your point and will change the license.  The Apache license will work just fine for our purposes.

**Comment by diegoveloper** [comment]
License was updated :) https://github.com/aeyrium/bezier-chart/blob/master/LICENSE

**Comment by bootstraponline** [comment]
Thank you! 😄

**Comment by ra9r** [comment]
No problem.  Please shoot us some screen shots if you can.  We'd love to see how you are using the lib.
