### ISSUE TITLE
Customizing labels

### ISSUE THREAD

**Issue by draskosaric** [aeyrium/bezier-chart#71]
Hi, first I like to congratulate you on this lib. It's great!

Now, I am making an app that should show blood pressure data in format number/number. I would represent it on chart in form of ratio but I would like to show the real values (130/80, for example) as a label.

How can I do it?

**Comment by diegoveloper** [comment]
Hi, you can check the samples , there is a footerBuilder method
https://github.com/aeyrium/bezier-chart/blob/master/example/lib/main.dart
