### ISSUE TITLE
The value of each object DatePoint is added up on chart

### ISSUE THREAD

**Issue by fagottino** [aeyrium/bezier-chart#72]
Hi, i'm trying to send my list of DataPoint to BezierLine, but it seems to sum entire xAxis value.

My list is
List<DataPoint> dataPoint = data.map((e) => 
DataPoint<DateTime>(
        value: double.parse(e[1]),
        xAxis: DateTime(
                DateTime.fromMillisecondsSinceEpoch((1000 * e[0]).toInt()).year,
                DateTime.fromMillisecondsSinceEpoch((1000 * e[0]).toInt()).month,
                DateTime.fromMillisecondsSinceEpoch((1000 * e[0]).toInt()).day)))
        .toList();

But the result on phone is the sum of xAxis value in list.

Can help me, please?

![photo_2020-03-17_21-15-52](https://user-images.githubusercontent.com/5007007/76906606-9f043600-68a4-11ea-8d83-9220732b488e.jpg)
![photo_2020-03-17_21-14-53](https://user-images.githubusercontent.com/5007007/76906651-b9d6aa80-68a4-11ea-9b46-e91216e1a654.jpg)

**Comment by diegoveloper** [comment]
Add a simple code sample that we could use to reproduce the issue.

**Comment by fagottino** [comment]
Hi @diegoveloper, thanks. 

In a Stateful Widget i have

List<DataPoint> dataPo = [];

List dataPoint = data.map((e) =>
DataPoint(
value: double.parse(e[1]),
xAxis: DateTime(
DateTime.fromMillisecondsSinceEpoch((1000 * e[0]).toInt()).year,
DateTime.fromMillisecondsSinceEpoch((1000 * e[0]).toInt()).month,
DateTime.fromMillisecondsSinceEpoch((1000 * e[0]).toInt()).day)))
.toList();

....
A ResponsiveGridCol that contain GraphWidget
ResponsiveGridCol(
lg: 18,
md: 18,
sm: 28,
xs: 28,
child: Center(
child: new GraphWidget(dataPoint: dataPo),
),
),

In GraphWidget class i have 

List<DataPoint> dataPoint = [];
GraphWidget({this.dataPoint});

....
series: [
BezierLine(
dataPointFillColor: Colors.black,
lineStrokeWidth: 4.0,
lineColor: Colors.green,
label: "Duty",
onMissingValue: (dateTime) {
 return 44.5;
},
data: dataPoint
),
],

The results is equals to the attached image on first post.

But if i change data property (who actually contain dataPoint) with the same code of example
data: [
DataPoint<DateTime>(value: 45.5,xAxis: DateTime(2019, 5, 26)),
DataPoint<DateTime>(value: 48.5, xAxis: DateTime(2019, 5, 30)),
]

the point on chart are shown correctly.

Sorry for my bad english, i'm Italian.

**Comment by diegoveloper** [comment]
Try using a single class main.dart that I could just copy and paste :).
Small simple code.

**Comment by fagottino** [comment]
Hi @diegoveloper, i solved with this property: **bezierChartAggregation: BezierChartAggregation.AVERAGE**. I think by default the chart does the sum of the data.

However is there any property that can make me set the number of decimals that the AVERAGE shows up?

Thank you.

**Comment by diegoveloper** [comment]
no , sorry there isn't at this moment, but you can send a PR if you want.
