### ISSUE TITLE
Create 15 minutes scale

### ISSUE THREAD

**Issue by JoeCapo87** [aeyrium/bezier-chart#73]
Hi @diegoveloper , i'm trying to create a scale to display data in 15 minutes steps, but even if i set 'Duration( minutes: (i + 15))', i have a point each minute. Where am i wrong?
I'm adding the class for you to check.

In the enum list i added a new item,   QUARTER.

<img width="341" alt="Schermata 2020-03-20 alle 13 26 17" src="https://user-images.githubusercontent.com/61780581/77163510-82d3e500-6aae-11ea-8e72-69bca9cdfbbf.png">
<img width="342" alt="Schermata 2020-03-20 alle 13 26 05" src="https://user-images.githubusercontent.com/61780581/77163518-86676c00-6aae-11ea-8ffb-f247ee366c56.png">

[bezier_chart_widget.txt](https://github.com/aeyrium/bezier-chart/files/4359476/bezier_chart_widget.txt)

**Comment by diegoveloper** [comment]
Could you add a screenshot or image about what you need?

**Comment by JoeCapo87** [comment]
> _i'm trying to create a scale to **display data in 15 minutes steps**, but even if i set 'Duration( minutes: (i + 15))', **i have a point each minute**_

I solved this, as you can see the time interval between points is exactly 15 minutes (11:29 - 11:44):
<img width="303" alt="Schermata 2020-03-21 alle 11 14 55" src="https://user-images.githubusercontent.com/61780581/77224390-7a8ab100-6b65-11ea-8f10-c174f4f2dd7f.png">
<img width="305" alt="Schermata 2020-03-21 alle 11 15 09" src="https://user-images.githubusercontent.com/61780581/77224392-7d85a180-6b65-11ea-8ce1-4b8b63779253.png">

The only problem is that the value for each point is wrong. It should vary as the time passes, but it stays the same.
