### ISSUE TITLE
Question : PopUp bubble

### ISSUE THREAD

**Issue by AlvaroVolker** [aeyrium/bezier-chart#76]
im trying to show bubble when i click one time on point not holding it, is it possible?

**Comment by AlvaroVolker** [comment]
@diegoveloper can you help?

**Comment by AlvaroVolker** [comment]
@diegoveloper could you help me? Please

**Comment by diegoveloper** [comment]
It only works using longPress for now because the chart could be scrolable

**Comment by AlvaroVolker** [comment]
@diegoveloper and it is possible to make the chart hourly with an scale like (00hs, 6hs, 12hs, 18hs, 24hs) not hour by hour?

**Comment by diegoveloper** [comment]
Use BezierChartScale.CUSTOM and use your own values :  

https://github.com/aeyrium/bezier-chart/blob/master/example/lib/main.dart#L189
