### ISSUE TITLE
can't get pinchZoom to work?

### ISSUE THREAD

**Issue by Riyad95** [aeyrium/bezier-chart#79]
thanks for maintaining this! I'm testing it out and the main feature that I was looking for is pinch to zoom.
All the examples have pinchZoom as false, switching it to true does nothing. 

I assume it's because a Scale is hard-coded in there. 
example: "bezierChartScale: BezierChartScale.WEEKLY"

I guess I need a function that checks if i zoomed in or out and returns the correct scale accordingly.

Now my question is, searching through the api i found no onZoom callback or something similar, am i missing something? or is there another way of achieving this?

thanks!

**Comment by diegoveloper** [comment]
Ok, pinchZoom is true by default.  Check the sample3 ( I updated minutes ago). https://github.com/aeyrium/bezier-chart/blob/dev/example/lib/main.dart#L354

using `onScaleChanged` you can identify when the scale changed according to the zoom.  
NOTE: Zoom only works when the indicator is hidden, so first, tap on the screen (to hide the indicator), then you can pinch/zoom.

Try sample 3 and sample 4.

**Comment by ManojMMWWIndia** [comment]
Zoom doesn't work from weekly to hourly & hourly-weekly. I've logged it as separate issue as well.
