### ISSUE TITLE
Graph moves to center of screen

### ISSUE THREAD

**Issue by maheshmnj** [aeyrium/bezier-chart#95]
HI @diegoveloper  thanks for the great package,I was wondering if there's any way to keep the axes aligned to edges. 
I mean if the x-Axis co-ordinates have limited values the graph moves to the center of the screen including the X and Y axis is there any way to keep the axis sticked to the edges and not move.
here's a sample output of the issue 
![Screenshot_20200806-115555](https://user-images.githubusercontent.com/31410839/89601539-6d573000-d882-11ea-9d2a-da3f84f1cef3.png)

Let me know if you need more info

**Comment by diegoveloper** [comment]
Hmm you can check the samples, you can set the width of the chart

**Comment by maheshmnj** [comment]
oh okay I think this answers my query got it, thanks as a workaround I added few extra values to xAxis.

**Comment by devrajraut** [comment]
@diegoveloper  Pls Can you Guide me how I can change the Width of the Chart? horizontalPadding is final inside BezierChartState and _contentWidth is private. How do it set the width when I define the BezierChart Widget? Thanks in advance.
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-08-18 at 12 27 17](https://user-images.githubusercontent.com/10286865/90480743-53550180-e14e-11ea-8ddd-2a250d45d704.png)
